export const CHANGE_SELECTED_TOOL = "CHANGE_SELECTED_TOOL";
export const CLOSE_SUB_OPTIONS = "CLOSE_SUB_OPTIONS";

export const CHANGE_PENCIL_COLOR = "CHANGE_PENCIL_COLOR";
export const CHANGE_PENCIL_THICKNESS = "CHANGE_PENCIL_THICKNESS";